openapi: 3.0.1
info:
  title: Generator for ProvysObject based classes
  description: Contains methods for geenrating classes, needed to implement access
    to objects from Provys database, described as entities in its metadata catalogue
  version: "1.0"
servers:
- url: /api
  variables: {}
paths:
  /entity/{entityNm}/proxy:
    get:
      summary: Generate Proxy
      description: Generate proxy - simple envelope on generated proxy file. Used
        only for initialisation, later not regenerated
      operationId: getProxy
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: friendEntities
        in: query
        schema:
          type: string
      responses:
        default:
          description: Class source
          content:
            text/plain:
              schema:
                type: string
  /entity/{entityNm}/interface:
    get:
      summary: Generate Interface
      description: Generate interface, representing instance of object of given type
      operationId: getInterface
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: friendEntities
        in: query
        schema:
          type: string
      responses:
        default:
          description: Class source
          content:
            text/plain:
              schema:
                type: string
  /entity/{entityNm}/value:
    get:
      summary: Generate Value
      description: Generate value class - object holding all object data
      operationId: getValue
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: friendEntities
        in: query
        schema:
          type: string
      responses:
        default:
          description: Class source
          content:
            text/plain:
              schema:
                type: string
  /entity/{entityNm}/dbloader:
    get:
      summary: Generate DbLoader class
      description: Generate database loader class - at the moment, does not generate
        load by methods.
      operationId: getDbLoader
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: friendEntities
        in: query
        schema:
          type: string
      responses:
        default:
          description: Class source
          content:
            text/plain:
              schema:
                type: string
  /entity/{entityNm}/dbloadrunner:
    get:
      summary: Generate DbLoadRunner class
      description: Generate database load runner class - class that actually fetches
        data from database and converts them to value objects.
      operationId: getDbLoadRunner
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: friendEntities
        in: query
        schema:
          type: string
      responses:
        default:
          description: Class source
          content:
            text/plain:
              schema:
                type: string
  /entity/{entityNm}/geninterface:
    get:
      summary: Generate GenInterface
      description: Generate generated ancestor of interface for accessing objects
        of given type, containing attribute getters
      operationId: getGenInterface
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: friendEntities
        in: query
        schema:
          type: string
      responses:
        default:
          description: Class source
          content:
            text/plain:
              schema:
                type: string
  /entity/{entityNm}/genproxy:
    get:
      summary: Generate GenProxy
      description: Generate generated proxy ancestor, implementing interface of given
        object in scope defined by generated interface
      operationId: getGenProxy
      parameters:
      - name: entityNm
        in: path
        required: true
        schema:
          type: string
      - name: friendEntities
        in: query
        schema:
          type: string
      responses:
        default:
          description: Class source
          content:
            text/plain:
              schema:
                type: string
